services:
  ui:
    build: ./ui
    image: ui
    env_file:
      - ./env/dev/ui.env
    ports:
      - "8080:8080"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - nats-demo
    depends_on:
      - nats

  nats:
    build: ./nats
    image: nats
    env_file:
      - ./env/dev/nats.env
    ports:
      - "1883:1883"
      - "4222:4222"
      - "8222:8222"
      - "9222:9222"
    volumes:
      - nats:/nats
    networks:
      - nats-demo

  prometheus-nats-exporter:
    image: natsio/prometheus-nats-exporter
    command: -varz -jsz=all http://nats:8222
    networks:
      - nats-demo
    depends_on:
      - nats

  prometheus:
    build: ./monitoring/prometheus
    image: prometheus
    volumes:
      - prometheus:/prometheus
    networks:
      - nats-demo
    depends_on:
      - prometheus-nats-exporter

  grafana:
    build: ./monitoring/grafana
    image: grafana
    env_file:
      - ./env/dev/grafana.env
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - nats-demo
    depends_on:
      - prometheus

networks:
  nats-demo:
    name: nats-demo

volumes:
  nats:
  caddy_data:
  caddy_config:
  prometheus:
  grafana:
